catkin build lio_sam ;
source /home/$USER/dev_ws/devel/setup.bash

# Get the current directory
CURR_DIR=$(pwd)
echo CURRENT DIR: $CURR_DIR

# Get the location of the slict package
ROS_PKG=lio_sam
echo FLIO DIR: $(rospack find $ROS_PKG)

CAPTURE_SCREEN=true;
LOG_DATA=true;

LAUNCH_FILE=run_ntuviral.launch
DATASET_LOC=/mnt/wwn-0x5002538e00000000-part1


EPOC_DIR=/home/$USER/MATLAB_WS/SLICT/liosam_ntuviral_20220917
#region Disable loop closure -----------------------------------------------------------------------------------------#


# EEE sequences
NTUVIRAL_SEQ=eee_01
ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;

NTUVIRAL_SEQ=eee_02
ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;

NTUVIRAL_SEQ=eee_03
ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;


# NYA sequences
NTUVIRAL_SEQ=nya_01
ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;

NTUVIRAL_SEQ=nya_02
ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;

NTUVIRAL_SEQ=nya_03
ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;


# SBS sequences
NTUVIRAL_SEQ=sbs_01
ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;

NTUVIRAL_SEQ=sbs_02
ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;

NTUVIRAL_SEQ=sbs_03
ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;


# # RTP sequences
# NTUVIRAL_SEQ=rtp_01
# ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
# LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
# ./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;

# NTUVIRAL_SEQ=rtp_02
# ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
# LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
# ./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;

# NTUVIRAL_SEQ=rtp_03
# ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
# LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
# ./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;


# # SPMS sequences
# NTUVIRAL_SEQ=spms_01
# ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
# LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
# ./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;

# NTUVIRAL_SEQ=spms_02
# ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
# LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
# ./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;

# NTUVIRAL_SEQ=spms_03
# ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
# LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
# ./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;


# # TNP sequences
# NTUVIRAL_SEQ=tnp_01
# ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
# LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
# ./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;

# NTUVIRAL_SEQ=tnp_02
# ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
# LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
# ./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;

# NTUVIRAL_SEQ=tnp_03
# ROSBAG_PATH=$DATASET_LOC/$NTUVIRAL_SEQ/${NTUVIRAL_SEQ}.bag
# LOG_PATH=$EPOC_DIR/result_$NTUVIRAL_SEQ
# ./run_one_bag.sh $LAUNCH_FILE $ROS_PKG $ROSBAG_PATH $CAPTURE_SCREEN $LOG_DATA $LOG_PATH 0;


#endregion Enable loop closure --------------------------------------------------------------------------------------#

